# Generated by Django 6.1.1 on 2026-10-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('price_per_gallon', models.FloatField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'city'], name='routing_fue_state_217c0f_idx'), models.Index(fields=['price_per_gallon'], name='routing_fue_price_p_d32ca8_idx')],
            },
        ),
    ]
