# Generated by Django 6.1.1 on 2026-10-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='coordinate_source',
            field=models.CharField(choices=[('census_city', 'Census city'), ('census_subdivision', 'Census county subdivision'), ('geonames_city', 'GeoNames city')], default='census_city', max_length=20),
        ),
    ]
